In [1]:
import requests
import sys
import pandas as pd
from difflib import get_close_matches
import smtplib 
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from flask import *

In [2]:
season_id = "1996-97"
player_info_url = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='.format(season_id)

In [3]:
for i in range(1996, 2020):
    season_id = str(i) + '-' + (str(i + 1)[2:4])
    player_info_url = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='.format(season_id)
    headers  = {
            'Connection': 'keep-alive',
            'Accept': 'application/json, text/plain, */*',
            'x-nba-stats-token': 'true',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36',
            'x-nba-stats-origin': 'stats',
            'Sec-Fetch-Site': 'same-origin',
            'Sec-Fetch-Mode': 'cors',
            'Referer': 'https://stats.nba.com/',
            'Accept-Encoding': 'gzip, deflate, br',
            'Accept-Language': 'en-US,en;q=0.9',
        }
    response = requests.get(url=player_info_url, headers=headers).json()
    player_info = response['resultSets'][0]['rowSet']
    column_headers = [
            'player_id', 'PLAYER', 'player_firstname', 'team_id', 'team_abv', 'player_age', 'GP',
            'player_gameswon', 'player_gameslost', 'unknown1', 'player_minutesplayed', 'player_FGmade', 'player_FGattemps',
            'FG_PCT', 'player_3PM', 'player_3PA', 'FG3_PCT', 'player_FTM', 'player_FTA', 'FT_PCT', 'player_OREB',
            'player_DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'unkown2', 'player_PF',
            'unkown3', 'PTS', 'player_+/-', 'player_FP', 'player_DD2', 'player_TD3', 'unknown4', 'unknown5', 'unknown6',
            'unknown7', 'unknown8', 'unknown9', 'unknown10', 'unknown11', 'unknown12', 'unknown13', 'unknown14', 'unknown15',
            'unknown16', 'unknown17', 'unknown18', 'unknown19', 'unknown20', 'unknown21', 'unknown22', 'unknown23', 'unknown24',
            'unknown25', 'unknown26', 'unknown27', 'unknown28', 'unknown29', 'unknown30', 'unknown31', 'unknown32', 'unknown33',
            'unknown34',
        ]
    nba_df = pd.DataFrame(player_info, columns = column_headers)
    nba

In [6]:
#nba_df = pd.DataFrame(player_info, columns = column_headers) 
#nba_df['player_namelower'] = nba_df['player_name'].str.lower()
#nba_df

In [9]:
#dataframe1 = pd.read_excel('NBAplayer_1948-1995.xlsx')
#dataframe1

,Column1,player_id,RANK,PLAYER,TEAM,GP,MIN,FGM,FGA,FG_PCT,...,REB,AST,STL,BLK,TOV,PTS,EFF,player_namelower,Sheet1,Year
0,0.0,600012,NaN,George Mikan,MNL,60,NaN,9.7,23.4,0.416,...,NaN,3.6,NaN,NaN,NaN,28.3,NaN,george mikan,Sheet1,1948-49
1,NaN,player_id,RANK,PLAYER,TEAM,GP,MIN,FGM,FGA,FG_PCT,...,REB,AST,STL,BLK,TOV,PTS,EFF,player_namelower,Sheet1,1949-50
2,NaN,600012,NaN,George Mikan,MNL,68,NaN,9.5,23.5,0.407,...,NaN,2.9,NaN,NaN,NaN,27.4,NaN,george mikan,Sheet1,1949-50
3,NaN,player_id,RANK,PLAYER,TEAM,GP,MIN,FGM,FGA,FG_PCT,...,REB,AST,STL,BLK,TOV,PTS,EFF,player_namelower,Sheet1,1950-51
4,NaN,600012,NaN,George Mikan,MNL,68,NaN,10,23.3,0.428,...,14.1,3.1,NaN,NaN,NaN,28.4,NaN,george mikan,Sheet1,1950-51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5554,179.0,432,180,Pete Chilcutt,HOU,74,8.8,1,2.4,0.408,...,2.1,0.4,0.3,0.2,0.3,2.7,3.8,pete chilcutt,NBAplayer_1995-96,1995-96
5555,180.0,29,181,Jim McIlvaine,WAS,80,14.9,0.8,1.8,0.428,...,2.9,0.1,0.3,2.1,0.5,2.3,5.6,jim mcilvaine,NBAplayer_1995-96,1995-96
5556,181.0,77142,NaN,Magic Johnson,LAL,32,29.9,4.3,9.2,0.466,...,5.7,6.9,0.8,0.4,3.2,14.6,NaN,magic johnson,NBAplayer_1995-96,1995-96
5557,182.0,891,NaN,Charles Oakley,NYK,53,33.5,4,8.5,0.471,...,8.7,2.6,1.1000000000000001,0.3,2,11.4,NaN,charles oakley,NBAplayer_1995-96,1995-96
5558,183.0,23,NaN,Dennis Rodman,CHI,64,32.6,2.3,4.8,0.48,...,14.9,2.5,0.6,0.4,2.2,5.5,NaN,dennis rodman,NBAplayer_1995-96,1995-96

In [26]:
#gamesarr = dataframe1.loc[(dataframe1["Year"] == "1984-85") & (dataframe1["player_id"] == 893), 'GP'].values
#print(gamesarr)
#playeridarr = dataframe1.loc[dataframe1['player_namelower'] == 'michael jordan', 'player_id'].values
#playeryear = dataframe1.loc[dataframe1['player_namelower'] == 'michael jordan', 'Year'].values
#print(playeridarr)
#print(playeryear)
#print(playeryear[0])
#(dataset["player_id"] == playeridarr[0])

[82]